version: '3.8'
services:
    client:
        stdin_open: true
        container_name: react-app-frontend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - '/app/node_modules'
            - './:/app'
        environment:
            - CHOKIDAR_USEPOLLING=true
